use_frameworks!

platform :ios, '8.0'

target 'BlinkLabel_Example' do
  pod 'BlinkLabel', :path => '../'

  target 'BlinkLabel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
